fullName = str(input("Nhập họ và tên: "))
Age = int(input("Nhập năm sinh: "))
Country = str(input("Nhập quê quán: "))
height = float(input("Nhập chiều cao: "))
weight = float(input("Nhập cân nặng: "))
level = str(input("Nhập xếp loại: "))
print("**********************************")
print("**********SƠ YẾU LÝ LỊCH**********")
print("**********************************")
print(f"Họ tên: {fullName}\nNăm sinh: {Age}\nQuê quán: {Country}\nChiều cao: {height}\nCân năng: {weight}\nTốt nghiệp loại: {level}")
